/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(dashboard)': RouteRecordInfo<
      '/(dashboard)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(dashboard)/assist/'
      | '/(dashboard)/knowledge/'
      | '/(dashboard)/org/'
      | 'ContractDetails'
      | 'assistApplications'
      | 'businessActivity'
      | 'client'
      | 'clientContacts'
      | 'clientList'
      | 'contact'
      | 'contactTask'
      | 'detail'
      | 'finance'
      | 'home'
      | 'platformConfig'
      | 'privilege'
      | 'roleList'
      | 'sale'
      | 'saleContract'
      | 'saleList'
      | 'stageApproval'
      | 'statistics'
      | 'userList'
    >,
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/assist/': RouteRecordInfo<
      '/(dashboard)/assist/',
      '/assist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'assistApplications': RouteRecordInfo<
      'assistApplications',
      '/assist-applications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'client': RouteRecordInfo<
      'client',
      '/client',
      Record<never, never>,
      Record<never, never>,
      | 'clientContacts'
      | 'clientList'
    >,
    'clientContacts': RouteRecordInfo<
      'clientContacts',
      '/client/contacts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'clientList': RouteRecordInfo<
      'clientList',
      '/client/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contact': RouteRecordInfo<
      'contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | 'businessActivity'
      | 'contactTask'
    >,
    'businessActivity': RouteRecordInfo<
      'businessActivity',
      '/contact/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'contactTask': RouteRecordInfo<
      'contactTask',
      '/contact/task',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'finance': RouteRecordInfo<
      'finance',
      '/finance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/knowledge/': RouteRecordInfo<
      '/(dashboard)/knowledge/',
      '/knowledge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(dashboard)/org/': RouteRecordInfo<
      '/(dashboard)/org/',
      '/org',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'privilege': RouteRecordInfo<
      'privilege',
      '/privilege',
      Record<never, never>,
      Record<never, never>,
      | 'platformConfig'
      | 'roleList'
      | 'userList'
    >,
    'platformConfig': RouteRecordInfo<
      'platformConfig',
      '/privilege/platform-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'roleList': RouteRecordInfo<
      'roleList',
      '/privilege/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'userList': RouteRecordInfo<
      'userList',
      '/privilege/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sale': RouteRecordInfo<
      'sale',
      '/sale',
      Record<never, never>,
      Record<never, never>,
      | 'ContractDetails'
      | 'detail'
      | 'saleContract'
      | 'saleList'
      | 'stageApproval'
    >,
    'saleContract': RouteRecordInfo<
      'saleContract',
      '/sale/contract',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ContractDetails': RouteRecordInfo<
      'ContractDetails',
      '/sale/contract-details/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'detail': RouteRecordInfo<
      'detail',
      '/sale/detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'saleList': RouteRecordInfo<
      'saleList',
      '/sale/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'stageApproval': RouteRecordInfo<
      'stageApproval',
      '/sale/stage-approval',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'statistics': RouteRecordInfo<
      'statistics',
      '/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(dashboard).page.vue': {
      routes:
        | '/(dashboard)'
        | '/(dashboard)/assist/'
        | '/(dashboard)/knowledge/'
        | '/(dashboard)/org/'
        | 'ContractDetails'
        | 'assistApplications'
        | 'businessActivity'
        | 'client'
        | 'clientContacts'
        | 'clientList'
        | 'contact'
        | 'contactTask'
        | 'detail'
        | 'finance'
        | 'home'
        | 'platformConfig'
        | 'privilege'
        | 'roleList'
        | 'sale'
        | 'saleContract'
        | 'saleList'
        | 'stageApproval'
        | 'statistics'
        | 'userList'
      views:
        | 'default'
    }
    'src/pages/(dashboard)/index.page.vue': {
      routes:
        | 'home'
      views:
        | never
    }
    'src/pages/(dashboard)/assist/index.page.vue': {
      routes:
        | '/(dashboard)/assist/'
      views:
        | never
    }
    'src/pages/(dashboard)/assist-applications/index.page.vue': {
      routes:
        | 'assistApplications'
      views:
        | never
    }
    'src/pages/(dashboard)/client.page.vue': {
      routes:
        | 'client'
        | 'clientContacts'
        | 'clientList'
      views:
        | 'default'
    }
    'src/pages/(dashboard)/client/contacts.page.vue': {
      routes:
        | 'clientContacts'
      views:
        | never
    }
    'src/pages/(dashboard)/client/list.page.vue': {
      routes:
        | 'clientList'
      views:
        | never
    }
    'src/pages/(dashboard)/contact.page.vue': {
      routes:
        | 'businessActivity'
        | 'contact'
        | 'contactTask'
      views:
        | 'default'
    }
    'src/pages/(dashboard)/contact/activity.page.vue': {
      routes:
        | 'businessActivity'
      views:
        | never
    }
    'src/pages/(dashboard)/contact/task.page.vue': {
      routes:
        | 'contactTask'
      views:
        | never
    }
    'src/pages/(dashboard)/finance.page.vue': {
      routes:
        | 'finance'
      views:
        | never
    }
    'src/pages/(dashboard)/knowledge/index.page.vue': {
      routes:
        | '/(dashboard)/knowledge/'
      views:
        | never
    }
    'src/pages/(dashboard)/org/index.page.vue': {
      routes:
        | '/(dashboard)/org/'
      views:
        | never
    }
    'src/pages/(dashboard)/privilege.page.vue': {
      routes:
        | 'platformConfig'
        | 'privilege'
        | 'roleList'
        | 'userList'
      views:
        | 'default'
    }
    'src/pages/(dashboard)/privilege/platform-config.page.vue': {
      routes:
        | 'platformConfig'
      views:
        | never
    }
    'src/pages/(dashboard)/privilege/role.page.vue': {
      routes:
        | 'roleList'
      views:
        | never
    }
    'src/pages/(dashboard)/privilege/user.page.vue': {
      routes:
        | 'userList'
      views:
        | never
    }
    'src/pages/(dashboard)/sale.page.vue': {
      routes:
        | 'ContractDetails'
        | 'detail'
        | 'sale'
        | 'saleContract'
        | 'saleList'
        | 'stageApproval'
      views:
        | 'default'
    }
    'src/pages/(dashboard)/sale/contract.page.vue': {
      routes:
        | 'saleContract'
      views:
        | never
    }
    'src/pages/(dashboard)/sale/contract-details/[id].page.vue': {
      routes:
        | 'ContractDetails'
      views:
        | never
    }
    'src/pages/(dashboard)/sale/detail/[id].page.vue': {
      routes:
        | 'detail'
      views:
        | never
    }
    'src/pages/(dashboard)/sale/list.page.vue': {
      routes:
        | 'saleList'
      views:
        | never
    }
    'src/pages/(dashboard)/sale/stage-approval.page.vue': {
      routes:
        | 'stageApproval'
      views:
        | never
    }
    'src/pages/(dashboard)/statistics.page.vue': {
      routes:
        | 'statistics'
      views:
        | never
    }
    'src/pages/login.page.vue': {
      routes:
        | 'login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
